import { ethers } from 'ethers';
import { type Investment, type InsertInvestment, type DailyReturn } from '@shared/schema';

export interface InvestmentProduct {
  name: string;
  minAmount: number;
  maxAmount: number;
  duration: number; // days
  apy: number;
  description: string;
  features: string[];
}

export const INVESTMENT_PRODUCTS: Record<string, InvestmentProduct> = {
  'BitNest Loop': {
    name: 'BitNest Loop',
    minAmount: 100,
    maxAmount: 100000,
    duration: 365, // 1 year
    apy: 12.5, // 12.5% APY
    description: 'Automated yield farming and liquidity provision system',
    features: [
      'Automated portfolio rebalancing',
      'Multi-protocol yield optimization', 
      'Smart contract security',
      'Compound interest rewards'
    ]
  },
  'BitNest Savings': {
    name: 'BitNest Savings',
    minAmount: 50,
    maxAmount: 50000,
    duration: 90, // 3 months
    apy: 8.5, // 8.5% APY
    description: 'Zero-risk savings with guaranteed returns',
    features: [
      'Principal protection guarantee',
      'Daily interest accrual',
      'Flexible withdrawal options',
      'Stablecoin focused'
    ]
  }
};

export class InvestmentService {
  private readonly PAYMENT_WALLET = '0xC8924fd9520540945E3Ce8A4b5282bacc380E825';

  calculateDailyReturn(amount: number, apy: number): number {
    return (amount * (apy / 100)) / 365;
  }

  calculateEndDate(startDate: Date, duration: number): Date {
    const endDate = new Date(startDate);
    endDate.setDate(endDate.getDate() + duration);
    return endDate;
  }

  async createInvestment(
    userId: string,
    productType: string,
    amount: number,
    walletAddress?: string
  ): Promise<InsertInvestment> {
    const product = INVESTMENT_PRODUCTS[productType];
    if (!product) {
      throw new Error('Invalid investment product');
    }

    if (amount < product.minAmount || amount > product.maxAmount) {
      throw new Error(`Investment amount must be between $${product.minAmount} and $${product.maxAmount}`);
    }

    const startDate = new Date();
    const endDate = this.calculateEndDate(startDate, product.duration);
    const dailyReturn = this.calculateDailyReturn(amount, product.apy);

    return {
      userId,
      productType,
      amount: amount.toString(),
      duration: product.duration,
      apy: product.apy.toString(),
      startDate,
      endDate,
      dailyReturn: dailyReturn.toString(),
      paymentWallet: this.PAYMENT_WALLET,
      status: 'active'
    };
  }

  async processPayment(investment: Investment, userWalletAddress: string): Promise<string> {
    try {
      // In a real implementation, this would create an actual blockchain transaction
      // For now, we simulate the payment processing
      
      const provider = new ethers.JsonRpcProvider('https://bsc-dataseed1.binance.org/');
      
      // Generate a mock transaction hash
      const mockTxHash = `0x${Math.random().toString(16).substring(2, 66)}`;
      
      console.log(`Processing payment: ${investment.amount} from ${userWalletAddress} to ${this.PAYMENT_WALLET}`);
      console.log(`Investment: ${investment.productType} for ${investment.duration} days`);
      console.log(`Generated transaction hash: ${mockTxHash}`);
      
      return mockTxHash;
    } catch (error: any) {
      throw new Error(`Payment processing failed: ${error?.message || 'Unknown error'}`);
    }
  }

  generateDailyReturns(investment: Investment): DailyReturn[] {
    const returns: DailyReturn[] = [];
    const currentDate = new Date(investment.startDate);
    const endDate = new Date(investment.endDate);
    const dailyReturn = parseFloat(investment.dailyReturn);

    while (currentDate <= endDate) {
      returns.push({
        id: '', // Will be generated by database
        investmentId: investment.id,
        date: new Date(currentDate),
        returnAmount: dailyReturn.toString(),
        processed: false,
        createdAt: new Date()
      });
      
      currentDate.setDate(currentDate.getDate() + 1);
    }

    return returns;
  }

  calculateTotalReturns(investment: Investment): number {
    const dailyReturn = parseFloat(investment.dailyReturn);
    return dailyReturn * investment.duration;
  }

  getInvestmentStatus(investment: Investment): string {
    const now = new Date();
    const endDate = new Date(investment.endDate);
    
    if (now > endDate) {
      return 'completed';
    }
    
    return investment.status;
  }

  getDaysRemaining(investment: Investment): number {
    const now = new Date();
    const endDate = new Date(investment.endDate);
    const diffTime = endDate.getTime() - now.getTime();
    return Math.max(0, Math.ceil(diffTime / (1000 * 60 * 60 * 24)));
  }
}

export const investmentService = new InvestmentService();